services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: forum_backend
    ports:
      - "8080:8080"
    volumes:
      - ./internal/db:/app/internal/db
    environment:
      - TZ=Europe/Athens
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: forum_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
